all:	analog dusty lcd buzz

dusty:	dusty.c
	gcc dusty.c -lmraa -lc -o dusty

buzz:	buzz.c
	gcc buzz.c -lmraa -lc -o buzz

lcd:	lcd.c
	gcc lcd.c -lmraa -lc -o lcd

analog:	analog.c
	gcc analog.c -lmraa -lc -o analog
